# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/camControl/main.go"
  bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp"]
  delay = 1000 # ms

[log]
  time = true