services:
  api:
    profiles:
      - all
      - api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=cameras
    depends_on:
      - db
    networks:
      - ptz-network

  db:
    profiles:
      - all
      - db
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=cameras
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - ptz-network

volumes:
  pgdata:

networks:
  ptz-network:
    driver: bridge
